---
name: callcenter-os
description: This is my personal OS image.
base-image: ghcr.io/aguslr/bluevanilla
image-version: latest
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
      - clamav
      - clamav-update
      - clamd
    remove:
      - firefox
      - firefox-langpacks
      - yelp
      - gnome-tour
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - com.hoptodesk.HopToDesk
        - org.onlyoffice.desktopeditors
        - org.gnome.Papers
        - org.gnome.Loupe
        - org.gnome.font-viewer
        - org.gnome.Calendar
        - org.gnome.Characters
        - org.gnome.Calculator
        - org.gnome.clocks
        - org.gnome.World.Secrets
        - com.belmoussaoui.Authenticator
        - com.github.jeromerobert.pdfarranger
        - com.github.huluti.Curtail
        - io.gitlab.adhami3310.Converter
        - com.vixalien.sticky
      remove:
        - org.gnome.eog
        - org.gnome.Evince
    user: {}
  - type: script
    snippets:
      - curl
        https://download.linphone.org/releases/linux/app/Linphone-5.2.6.AppImage
        > /usr/libexec/linphone.AppImage
      - chmod +x /usr/libexec/linphone.AppImage
  - type: script
    snippets:
      - chmod +x /etc/clamav/detected.sh
      - freshclam
  - type: systemd
    user:
      enabled:
        - clamav-scan.service
        - clamav-scan.timer
  - type: signing
