---
name: callcenter-os
description: This is my personal OS image.
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41
modules:
  - type: files
    files:
      - source: system
        destination: /
  - type: rpm-ostree
    repos:
      - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - micro
      - starship
    remove:
      - firefox
      - firefox-langpacks
  - type: default-flatpaks
    notify: true
    system:
      install:
        - org.mozilla.firefox
        - org.gnome.Loupe
        - com.github.jkotra.eovpn
        - com.hoptodesk.HopToDesk
      remove:
        - org.gnome.eog
    user: {}
  - type: script
    snippets:
      - curl
        https://download.linphone.org/releases/linux/app/Linphone-5.2.6.AppImage
        > /usr/libexec/linphone.AppImage
  - type: signing
